python src/ginfinity/scripts/embed_msa.py \
  --input /home/nicolas/ginfinity_applications/premirnas/premirans_node_embeds.tsv \
  --name-col Name \
  --embeds-col node_embeddings \
  --dotbracket-col DotBracket \
  --paired-col PairedIndices \
  --topk 80 \
  --consistency-rounds 30 \
  --alpha 10.0 \
  --beta -0.65 \
  --gap-open -3.5 \
  --gap-extend -3.5 \
  --use-local \
  --tree nj \
  --refine-iters 40 \
  --num-workers 16 \
  --max-pairs 2000 \
  --seed 42 \
  --plot-diagnostics
